repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Using a recent version of ruff-pre-commit compatible with Ruff
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
